name: PR Checks

on:
  pull_request:
    branches:
      - main

# Cancel in-progress runs when a new commit is pushed to the PR
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.12.0

      - name: Install dependencies
        run: npm ci

      # Run oxlint. Errors and warnings will be added as annotations to the PR
      - name: Lint code
        run: npm run lint -- --format=github
